# Decadal Mean Value Analysis

In [123]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pymannkendall as mann_kendall
import itertools
from scipy.stats import kendalltau, pearsonr, spearmanr

## Reading Files

In [124]:
dataset = 'camels_USA'

output_version = '1'

path = f'C:/users/creeb/ThesisGit/Thesis_Git_MOH/{dataset}/'

index_file = f'camels_USA_table.xlsx'

fignum = 0  # iusing a cumulative count of fignum is useful

indexes = pd.read_excel(path+index_file)

EE_list = indexes.system_index.to_list()

catchment_list = indexes.loc[:, 'hru_id']

index_list = [i for i in zip(EE_list, catchment_list)]

In [125]:
ex_df = pd.read_excel(path + str(7261000) +'_decadal.xlsx', index_col=0, parse_dates=True)

In [126]:
ex_df

,B1,B2,B3,B4,B5,B7,ndvi,evi,nbr,ndmi,gndvi,ndbi,BRIGHTNESS,GREENNESS,WETNESS
1984-08-31 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1985-08-31 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986-08-31 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-08-31 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-08-31 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1989-08-31 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-08-31 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-08-31 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-08-31 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-08-31 22:00:00,478.566365,708.142867,630.823903,3209.321066,2202.940675,1098.356342,0.674333,-0.151195,0.494548,0.189651,0.640890,-0.189651,3524.305393,1801.349835,-1304.869446
1994-08-31 22:00:00,502.123121,720.773780,637.699909,3242.581346,2186.957226,1081.490537,0.675320,-0.158175,0.504555,0.198502,0.639540,-0.198502,3548.385580,1819.471066,-1272.958419
1995-08-31 22:00:00,469.889664,701.246771,611.835618,3276.256398,2138.743602,1034.258632,0.689272,-0.169808,0.524340,0.213826,0.650865,-0.213826,3512.786923,1876.481562,-1218.907319
1996-08-31 22:00:00,501.523754,724.794320,634.152097,3301.700901,2144.915689,1045.010466,0.682669,-0.172905,0.523704,0.216323,0.644196,-0.216323,3560.380458,1872.408598,-1212.942478
1997-08-31 22:00:00,492.421736,715.131266,624.225476,3310.312837,2123.352498,1027.586775,0.687840,-0.176867,0.530643,0.222198,0.649154,-0.222198,3543.214649,1890.851117,-1191.568548
1998-08-31 22:00:00,511.176711,724.808004,636.681601,3307.342440,2133.073543,1041.013224,0.683320,-0.175938,0.526144,0.219929,0.645900,-0.219929,3562.374302,1874.669066,-1200.450051
1999-08-31 22:00:00,497.676829,713.353978,637.336360,3247.977399,2140.738801,1049.388762,0.678308,-0.168402,0.516774,0.209745,0.645424,-0.209745,3525.457423,1831.390450,-1222.783427
2000-08-31 22:00:00,500.587868,714.848253,648.249506,3208.637398,2161.134567,1067.338515,0.670119,-0.161233,0.505837,0.199255,0.641221,-0.199255,3520.622261,1791.282454,-1250.122137
2001-08-31 22:00:00,504.319198,718.782563,648.891219,3224.112195,2170.345271,1072.843316,0.671217,-0.161770,0.505778,0.199560,0.640976,-0.199560,3536.404201,1800.747771,-1256.175422
2002-08-31 22:00:00,479.050482,692.008017,623.325089,3179.401817,2161.801397,1064.937619,0.678264,-0.156794,0.503545,0.194898,0.647525,-0.194898,3475.828199,1790.605251,-1266.795420
2003-08-31 22:00:00,474.880835,688.641712,613.812896,3203.240508,2144.513969,1051.575178,0.684386,-0.161511,0.510764,0.202116,0.651094,-0.202116,3473.529926,1817.779511,-1246.828950
2004-08-31 22:00:00,445.109938,668.571534,592.842674,3196.104961,2134.531368,1040.805933,0.691734,-0.160787,0.513163,0.202809,0.657850,-0.202809,3437.823361,1834.449881,-1246.092195
2005-08-31 22:00:00,450.463585,672.381013,599.424058,3189.470429,2156.561265,1061.198111,0.688369,-0.156785,0.505232,0.196882,0.655705,-0.196882,3451.906222,1821.049611,-1271.620788
2006-08-31 22:00:00,419.159455,647.533762,576.929945,3159.166325,2160.392085,1061.008435,0.694674,-0.151479,0.501639,0.191508,0.662545,-0.191508,3406.509034,1820.135901,-1291.928029
2007-08-31 22:00:00,420.253064,650.162451,578.578891,3152.493880,2161.029874,1063.670824,0.693345,-0.150884,0.499829,0.190261,0.660791,-0.190261,3405.718087,1812.722948,-1293.974939
2008-08-31 22:00:00,383.088558,626.116726,554.437772,3149.963452,2131.437872,1038.471451,0.702377,-0.153271,0.507797,0.196129,0.669364,-0.196129,3358.290937,1839.010724,-1272.362574
2009-08-31 22:00:00,377.273544,617.896659,539.891824,3172.016830,2107.209635,1018.462896,0.710952,-0.159085,0.517460,0.204823,0.675049,-0.204823,3346.133817,1869.845543,-1246.490903
2010-08-31 22:00:00,376.335412,613.067693,534.367764,3175.955765,2099.910955,1012.221626,0.713609,-0.160359,0.519935,0.206892,0.677500,-0.206892,3339.426652,1878.114244,-1239.801811
2011-08-31 22:00:00,364.897028,600.696152,524.916005,3162.279582,2084.588663,1001.642444,0.716588,-0.160642,0.521793,0.208019,0.681616,-0.208019,3311.649986,1878.772777,-1230.883154
2012-08-31 22:00:00,379.941761,618.629168,562.455591,3131.315346,2151.212730,1066.692508,0.696530,-0.145291,0.496174,0.189232,0.670318,-0.189232,3360.934860,1818.778590,-1305.159326
2013-08-31 22:00:00,380.824376,621.774529,567.552846,3120.103579,2160.480169,1078.553143,0.693621,-0.143217,0.490706,0.185466,0.668127,-0.185466,3364.428720,1804.616400,-1318.254915
2014-08-31 22:00:00,373.299364,616.809268,560.650322,3107.247287,2153.194740,1079.464115,0.695717,-0.142890,0.488912,0.185252,0.669095,-0.185252,3347.566881,1800.289906,-1319.283938
2015-08-31 22:00:00,357.660367,605.237740,541.554646,3123.248960,2127.881192,1058.562986,0.705651,-0.147819,0.498053,0.193293,0.675476,-0.193293,3325.477020,1831.213352,-1295.491084
2016-08-31 22:00:00,352.556780,602.217591,529.982643,3150.986862,2100.063367,1035.657594,0.713041,-0.154364,0.509162,0.203578,0.679101,-0.203578,3318.745134,1863.934041,-1262.504716
2017-08-31 22:00:00,342.077064,594.656689,515.472645,3180.248331,2078.474486,1017.801158,0.721838,-0.159784,0.518817,0.212851,0.684791,-0.212851,3311.387288,1900.724556,-1238.597719
2018-08-31 22:00:00,343.624305,596.025710,519.225113,3172.120473,2089.620645,1030.921542,0.719696,-0.157317,0.513542,0.209379,0.683561,-0.209379,3316.182973,1889.886182,-1254.005186
2019-08-31 22:00:00,346.656484,604.540342,521.469063,3201.058113,2087.179221,1030.915611,0.720578,-0.160401,0.516453,0.213985,0.682103,-0.213985,3337.431420,1908.870516,-1245.214876
2020-08-31 22:00:00,335.176716,597.172667,504.285155,3220.051718,2057.170643,1007.037548,0.730378,-0.166811,0.527596,0.223973,0.687224,-0.223973,3318.560665,1939.805903,-1214.357416
2021-08-31 22:00:00,327.274628,593.592804,490.507431,3244.593664,2029.686034,984.820622,0.738723,-0.173375,0.538503,0.234050,0.690880,-0.234050,3308.233728,1971.584069,-1183.413341
2022-08-31 22:00:00,311.075792,580.507489,459.748100,3291.877774,1975.804773,934.439155,0.756642,-0.188303,0.560592,0.252442,0.701242,-0.252442,3281.202427,2037.885667,-1121.122980

## Three decadal periods for which parameters are calculated from Water Balance

This is individual for the Meuse basin dataset. Camels GB for example is longer. 

-->1981-1989 --  1990 - 1999 -- 2000-2009

we take the following slices:

--> [ NA ] -- [ 12 ] -- [ 21 ]

In [127]:
  #Read and list the catchment IDs used

keys_list = ex_df.keys().to_list()   #The Keys used here are the bands and indices from the decadal average table

print(keys_list[:])   #should print all bands/indices keys within the decadal average table

bracket1, bracket2, bracket3 = '1980 - 1989', '1990 - 1999', '2000 - 2009'
slice1, slice2, slice3 = 1, 12, 21

#fignum+=1
#plt.figure(fignum, figsize=(20,10))

mk_list = []

br_means = []  # the values conforming with the slices defined by the LT water balance effort


for keys in keys_list[:]:
    fignum+=1
    '''
    Looping through the keys (bands and indices generated from the landsat surface reflectances)
    
    --> inner loop says: for this key, loop through each file and chart the timeseries
    
    charting is slow and commented out, but will overlay all timeseries available if run
    '''
#    plt.figure(fignum, figsize=(20,10))
#    plt.title(keys)
    
    for ind in index_list:
        df = pd.read_excel(path + str(ind[1]) +'_decadal.xlsx', index_col=0, parse_dates=True)
        
        loc = df.loc[:, keys]
        
        br_means.append([ind[0], keys, ind[1], loc[slice1], loc[slice2], loc[slice3], ])
#        x = df.loc[:, keys_list[0]]
#        plt.plot(loc, label=ind[16:])
#        plt.legend(bbox_to_anchor=(1,1),ncol=2, loc="upper left")
        temp_mk_list = list(mann_kendall.original_test(loc))
        temp_mk_list.append(keys)
        temp_mk_list.append(ind[0])
        temp_mk_list.append(ind[1])
        mk_list.append(temp_mk_list)
        
        if ind[1] == 3366500:
            break

print('done')

['B1', 'B2', 'B3', 'B4', 'B5', 'B7', 'ndvi', 'evi', 'nbr', 'ndmi', 'gndvi', 'ndbi', 'BRIGHTNESS', 'GREENNESS', 'WETNESS']
done

# What to do with these averages? 

* Can we get a table of deltas? e.g. what if the NDVI delta can be used to predict the deviation in the Budyko framework?
* Establish a table of deltas, use fitted slope?

In [128]:
'''
Creating the spectral average table with matching brakets of dates
'''

headers = [f'system_index', f'band', f'ID', f'{bracket1}', f'{bracket2}', f'{bracket3}']

datatype = {f'system_index': str,
            f'band':str, 
            f'ID':int, 
            f'{bracket1}':float, 
            f'{bracket2}':float, 
            f'{bracket3}':float,}

decadal_df = pd.DataFrame(br_means, columns=headers).astype(datatype)

d_groups = decadal_df.groupby(['band']).groups

USA = pd.read_csv('USA.csv', skipinitialspace=True)

USA.rename(columns = {'Unnamed: 0':'ID'}, inplace = True)

camels_indices = USA.keys().to_list()

#decadal_df#.iloc[d_groups['ndvi']]
[for i in zip(USA.id.values, USA.AI.values, USA.EI.values, USA.)]

SyntaxError: invalid syntax (2101938165.py, line 25)

In [ ]:
WB_indices = ['AI',
              'EI',
#              'Ep',
#              'HAI',
#              'Epa',
#              'P',
#              'Pa',
              'SI',
              'ST',
              'T',
              'is_dur',
              'omega',
#              'dp',
#              'sp',
#              'dt',
#              'st',
#              'sd',
#              'de',
#              'se',
              'Sr actual',]

In [ ]:
from scipy.stats import kendalltau, pearsonr, spearmanr

def kendall_pval(x,y):
    return kendalltau(x,y)[1]

def pearsonr_pval(x,y):
    return pearsonr(x,y)[1]

def spearmanr_pval(x,y):
    return spearmanr(x,y)[1]

In [ ]:
def combine_decadal_tables(indices:[], keys_list):
    
    '''
    Passing climatic / LT WB indices
    
    generate dataframe with columns: 
    [ "system_index", "catchment_name", "decade_ending", "country_code",  "index_name"]

    '''
    key=keys_list[0]
    
    SR_ndvi = decadal_df.iloc[d_groups[key]]   #Surface Reflectance

    df = pd.merge(SR_ndvi, USA, on='ID')
    
    x2 = df.loc[:, f'{bracket2}']
    AI_2 = df.loc[:, 'AI']
    EI_2 = df.loc[:, 'EI']
    SR_2 = df.loc[:, 'Sr']
    Catchment_x2 = df.loc[:, 'ID']
    decade_x2 = [1999 for i in range(len(x2))]
    SID_x2 = df.loc[:, 'system_index']

    country_x2 = ['USA' for i in range(len(x2))]
    
    
    x3 = df.loc[:, f'{bracket3}']
    AI_3 = df.loc[:, 'AI']
    EI_3 = df.loc[:, 'EI']
    SR_3 = df.loc[:, 'Sr']
    SID_x3 = df.loc[:, 'system_index']
    Catchment_x3 = df.loc[:, 'ID']
    decade_x3 = [2009 for i in range(len(x3))]
    country_x3 = ['USA' for i in range(len(x3))]
    
    SR_index_values = list(itertools.chain(*(x2.to_list(),
                                             x3.to_list(),))) 

    SID = list(itertools.chain(*(SID_x2.to_list(),
                                 SID_x3.to_list(),)))

    country_code = list(itertools.chain(*(country_x2, 
                                          country_x3,)))

    catchment_name = list(itertools.chain(*(Catchment_x2.to_list(),
                                            Catchment_x3.to_list(),)))

    decade_ending = list(itertools.chain(*(decade_x2, 
                                          decade_x3,)))
    
    AI = list(itertools.chain(*(AI_2.to_list(),
                                             AI_3.to_list(),)))
    
    EI = list(itertools.chain(*(EI_2.to_list(),
                                             EI_3.to_list(),)))
    
    SR = list(itertools.chain(*(SR_2.to_list(),
                                             SR_3.to_list(),)))
    
    dict_ = { "system_index":SID, 
             "country_code":country_code,
             "catchment_name":catchment_name, 
             "decade_ending":decade_ending, 
             "LT_AI":AI, 
             "LT_EI":EI, 
             "LT_SR":SR, 
             key:SR_index_values}
    
    dict_dtype = { "system_index":str, 
             "country_code":str,
             "catchment_name":str, 
             "decade_ending":int,
                  "LT_AI":float, 
             "LT_EI":float, 
             "LT_SR":float, 
             key:float}
    
    df_all = pd.DataFrame(dict_).astype(dict_dtype)
    
    for key in keys_list[1:]:
        SR_ndvi = decadal_df.iloc[d_groups[key]]
 
        df = pd.merge(SR_ndvi, USA, on='ID')
        
        x2 = df.loc[:, f'{bracket2}']
        
        x3 = df.loc[:, f'{bracket3}']

        
        SR_index_values = list(itertools.chain(*(x2.to_list(),
                                             x3.to_list(),))) 
        
        df_all[key] = SR_index_values
    
    for i in indices:

        y2 = df.loc[:, f'{i} {bracket2}']
        
        
        y3 = df.loc[:, f'{i} {bracket3}']
        
        WB_values = list(itertools.chain(*(y2.to_list(),
                                            y3.to_list(),)))

        df_all[i] = WB_values
    
    #for j in df_all.catchment_name:

        
    prs_r = df_all.corr()
    
    p = df_all.corr(method=pearsonr_pval)
    
    return [df_all, prs_r, p]

In [ ]:
df_all, prs_r, p = combine_decadal_tables(WB_indices[0:], keys_list[:])# for i in keys_list[7:]][0]
df_all.to_excel(f'camels_USA/{dataset}_all_decadal_indices_combined_{output_version}.xlsx')
prs_r.to_excel(f'camels_USA/{dataset}_all_decadal_indices_r_values_{output_version}.xlsx')
display(df_all.iloc[0, :])
display(df_all.iloc[int(len(df_all)/2), :])
#df_depart['new_col'] = np.where(df_depart['NOM SCADA'].isin(data_sorted_monotone.columns), 'smth', np.nan)

In [ ]:
p.to_excel(f'camels_USA/{dataset}_all_decadal_indices_p_values_sorted_{output_version}.xlsx')

p.replace(1, np.nan)
sorted_p = pd.DataFrame()

for i in p.keys()[7:]:
    sort = pd.DataFrame(p.loc[:, i].sort_values(ascending=False))
    sorted_p[f'{i}_vs'] = sort.index
    sorted_p[f'{i}_p'] = sort.values
sorted_p

In [ ]:
def combine_change_tables(indices:[], keys_list):
    
    '''
    Passing climatic / LT WB indices
    
    generate dataframe with columns: 
    [ "system_index", "catchment_name", "decade_ending", "country_code",  "index_name"]

    '''
    
    key = keys_list[0] 
    
    SR_ndvi = decadal_df.iloc[d_groups[key]]

    df = pd.merge(SR_ndvi, USA, on='ID')
    
    x2 = df.loc[:, f'{bracket2}']
    AI_2 = df.loc[:, 'AI']
    EI_2 = df.loc[:, 'EI']
    SR_2 = df.loc[:, 'Sr']

    x3 = df.loc[:, f'{bracket3}']
    
    delta2 = x3 - x2  #delta = new - old
    
    SID = df.loc[:, 'system_index']
    
    catchment_name = df.loc[:, 'ID']
    
    decade_ending = [2009 for i in range(len(delta2))]
    
    country_code = ['USA' for i in range(len(delta2))]
    
    dict_ = { "system_index":SID, 
             "country_code":country_code,
             "catchment_name":catchment_name, 
             "decade_ending":decade_ending, 
             "LT_AI":AI, 
             "LT_EI":EI, 
             "LT_SR":SR, 
             f'd_{key}':delta2}
    
    dict_dtype = { "system_index":str, 
             "country_code":str,
             "catchment_name":str, 
             "decade_ending":int, 
                  "LT_AI":float, 
             "LT_EI":float, 
             "LT_SR":float, 
             f'd_{key}':float}
    
    df_all = pd.DataFrame(dict_).astype(dict_dtype)
    
    for key in keys_list[1:]:
        SR_ndvi = decadal_df.iloc[d_groups[key]]
 
        df = pd.merge(SR_ndvi, USA, on='ID')
        
        x2 = df.loc[:, f'{bracket2}']
        
        x3 = df.loc[:, f'{bracket3}']
        
        delta2 = x3 - x2
        
        df_all[f'd_{key}'] = delta2
    
    for i in indices:

        y2 = df.loc[:, f'{i} {bracket2}']
        
        
        y3 = df.loc[:, f'{i} {bracket3}']
        
        WB_delta = y3 - y2

        df_all[f'd_{i}'] = WB_delta
        
    prs_r = df_all.corr()
    
    p = df_all.corr(method=pearsonr_pval)
    
    return [df_all, prs_r, p]

In [ ]:
df_delta_all, prs_delta_r, delta_p = combine_change_tables(WB_indices[0:], keys_list[:])

df_delta_all.to_excel(f'camels_USA/{dataset}_all_decadal_delta_{output_version}.xlsx')
prs_delta_r.to_excel(f'camels_USA/{dataset}_all_decadal_delta_r_values_{output_version}.xlsx')
delta_p.to_excel(f'camels_USA/{dataset}_all_decadal_delta_p_values_sorted_{output_version}.xlsx')


prs_delta_r

In [ ]:
delta_p.replace(1, np.nan)
sorted_delta_p = pd.DataFrame()

for i in delta_p.keys()[7:]:
    sort = pd.DataFrame(delta_p.loc[:, i].sort_values(ascending=False))
    sorted_delta_p[f'{i}_vs'] = sort.index
    sorted_delta_p[f'{i}_p'] = sort.values
    
prs_delta_r

In [ ]:
def plot_descending_P(SR_index:[], df_all, sorted_p, prs_r, delta=False):
    '''
    The function loops through the list of Surface Reflectance indices passed. The plotting returns scatters in descending
    order from   to:  1 > p-value > 0.01 
    '''
    
    
    for i in SR_index:
        
        if delta==True:
            i = f'd_{i}'

        high_to_low_id = sorted_p.loc[:, f'{i}_vs']
        high_to_low_p = sorted_p.loc[:, f'{i}_p']
        
        for j in zip(high_to_low_id, high_to_low_p):
            if j[1] < 1:
                plt.figure()
                
                r = prs_r.loc[i, j[0]]
                
                plt.title(f'{j[0]} vs {i}, p: {j[1]:.3f}, r= {r:.3f}')
                
                x = df_all.loc[:, i] 
                
                y = df_all.loc[:, j[0]]
                
                plt.xlabel(i)
                
                plt.ylabel(j[0])
                
                if delta==True:

                    plt.scatter(x, y, alpha=0.6)

                else:    
                    levels = [1989, 1999, 2009]

                    plt.scatter(x, y, c=df_all.loc[:,  'decade_ending'], alpha=0.6)
                    plt.colorbar(ticks=levels)
                
                if j[1] <= 0.1:
                    break
                
            else:
                None

In [ ]:
plot_descending_P(['ndvi'], df_delta_all, sorted_delta_p, prs_delta_r, delta=True)

In [ ]:
plot_descending_P(['ndvi'], df_all, sorted_p, prs_r, delta=False)

## Export MK trends to Table

- derived from spectral bands and indices the timeseries are tested for significance of trend
- plots are the distribution of slope of trend currently

In [ ]:
mk = np.array(mk_list)

data_types_dict = {'trend': str, 'h':bool, 'p':float, 'z':float, 'Tau':float, 's':float, 'var_s':float, 'slope': float, 'intercept':float, 'band':str, 'system_index':str}

mk_dict = {'trend': mk[:, 0], 
           'h':mk[:, 1], 
           'p':mk[:, 2], 'z':mk[:, 3], 'Tau':mk[:, 4], 's':mk[:, 5], 'var_s':mk[:, 6], 'slope': mk[:, 7], 'intercept':mk[:, 8], 'band':mk[:, 9], 'system_index':mk[:, 10]}

mk_df = pd.DataFrame(mk_dict).astype(data_types_dict)

groups = mk_df.groupby(['band']).groups
keys = groups.keys()
B1 = mk_df[groups['B1'][0]:groups['B1'][-1]]

def export_key_MK_tables(key, groups):
    frm_ind = groups[key][0]
    to_ind = groups[key][-1]
    key_df = mk_df[groups[key][0]:groups[key][-1]]
    key_df.to_excel(f'{path}mk_trends/mk_{str(key)}.xlsx')

[export_key_MK_tables(key, groups) for key in keys]

fignum=0

def hist(band):
    frm_ind = groups[band][0]
    to_ind = groups[band][-1]
    key_df = mk_df[frm_ind:to_ind]
    plt.figure()
    x = np.array(key_df.slope)
    print(f'{band}: min:{np.min(x)}, max:{np.max(x)}')
    plt.hist(x)
    plt.title(f'{band}')
    
    
[hist(key) for key in keys]

In [ ]:
fignum=0

def hist(band):
    frm_ind = groups[band][0]
    to_ind = groups[band][-1]
    key_df = mk_df[frm_ind:to_ind]
    plt.figure()
    x = np.array(key_df.p)
    print(f'{band}: min:{np.min(x)}, max:{np.max(x)}')
    plt.hist(x)
    plt.title(f'{band}')
    
    
[hist(key) for key in keys]